### ISSUE TITLE
support GNOME 45

### ISSUE THREAD

**Issue by jorp** [coffeverton/weekend-o-meter#2]
simply editing the `shell-version` field to include `45` in `~/.local/share/gnome-shell/extensions/weekend-o-meter*/metadata.json` doesn't work as a quick fix

**Comment by coffeverton** [comment]
Hi!
I just read that there are some breaking changes on how Gnome 45 deal with extensions.

I'll try to find some time to install another distro to do some testing, but it can take some time.
